import type { Corridor, District, Mission, Vehicle } from './types'

export const corridors: Corridor[] = [
  { id: 'NH-6-S42', name: 'NH-6 · Segment 42', startLocation: 'Guwahati', endLocation: 'Aizawl', districts: ['KAM', 'AIZ'], riskScore: 84, alternateRouteIds: ['NH-27-GD', 'NH-37-GS'], capacity: 'Medium', travelTime: 260 },
  { id: 'NH-27-GD', name: 'NH-27 · Guwahati–Dimapur', startLocation: 'Guwahati', endLocation: 'Dimapur', districts: ['KAM', 'DIM'], riskScore: 48, alternateRouteIds: ['NH-6-S42', 'NH-29-DK'], capacity: 'High', travelTime: 230 },
  { id: 'NH-29-DK', name: 'NH-29 · Dimapur–Kohima', startLocation: 'Dimapur', endLocation: 'Kohima', districts: ['DIM', 'KOH'], riskScore: 57, alternateRouteIds: ['NH-27-GD', 'NH-2-KI'], capacity: 'Medium', travelTime: 180 },
  { id: 'NH-2-KI', name: 'NH-2 · Kohima–Imphal', startLocation: 'Kohima', endLocation: 'Imphal', districts: ['KOH', 'IMP'], riskScore: 63, alternateRouteIds: ['NH-29-DK', 'NH-37-GS'], capacity: 'Low', travelTime: 250 },
  { id: 'NH-37-GS', name: 'NH-37 · Guwahati–Shillong', startLocation: 'Guwahati', endLocation: 'Shillong', districts: ['KAM', 'EKB'], riskScore: 41, alternateRouteIds: ['NH-27-GD', 'NH-6-S42'], capacity: 'High', travelTime: 150 },
  { id: 'NH-44-SH', name: 'NH-44 · Shillong–Silchar', startLocation: 'Shillong', endLocation: 'Silchar', districts: ['EKB', 'CAC'], riskScore: 52, alternateRouteIds: ['NH-6-S42'], capacity: 'Medium', travelTime: 210 },
  { id: 'NH-306-SI', name: 'NH-306 · Silchar–Aizawl', startLocation: 'Silchar', endLocation: 'Aizawl', districts: ['CAC', 'AIZ'], riskScore: 68, alternateRouteIds: ['NH-44-SH', 'NH-6-S42'], capacity: 'Low', travelTime: 245 },
  { id: 'NH-102-IJ', name: 'NH-102 · Imphal–Jiribam', startLocation: 'Imphal', endLocation: 'Jiribam', districts: ['IMP', 'CAC'], riskScore: 61, alternateRouteIds: ['NH-2-KI', 'NH-44-SH'], capacity: 'Medium', travelTime: 220 },
  { id: 'NH-15-TI', name: 'NH-15 · Tawang Access', startLocation: 'Tezpur', endLocation: 'Tawang', districts: ['WKA'], riskScore: 76, alternateRouteIds: ['NH-27-GD'], capacity: 'Low', travelTime: 360 },
  { id: 'NH-52-IT', name: 'NH-52 · Itanagar–Tezpur', startLocation: 'Itanagar', endLocation: 'Tezpur', districts: ['PAP'], riskScore: 54, alternateRouteIds: ['NH-27-GD', 'NH-15-TI'], capacity: 'Medium', travelTime: 205 },
]
export const districts: District[] = [
  { id: 'KAM', name: 'Kamrup Metro', state: 'Assam', accessibilityScore: 92, population: 1250000, essentialSupplyRisk: 18 }, { id: 'AIZ', name: 'Aizawl', state: 'Mizoram', accessibilityScore: 61, population: 404000, essentialSupplyRisk: 72 }, { id: 'DIM', name: 'Dimapur', state: 'Nagaland', accessibilityScore: 78, population: 379000, essentialSupplyRisk: 39 }, { id: 'KOH', name: 'Kohima', state: 'Nagaland', accessibilityScore: 64, population: 267000, essentialSupplyRisk: 58 }, { id: 'IMP', name: 'Imphal West', state: 'Manipur', accessibilityScore: 59, population: 517000, essentialSupplyRisk: 68 }, { id: 'EKB', name: 'East Khasi Hills', state: 'Meghalaya', accessibilityScore: 74, population: 825000, essentialSupplyRisk: 44 }, { id: 'CAC', name: 'Cachar', state: 'Assam', accessibilityScore: 81, population: 1730000, essentialSupplyRisk: 33 }, { id: 'WKA', name: 'West Kameng', state: 'Arunachal Pradesh', accessibilityScore: 48, population: 87000, essentialSupplyRisk: 82 }, { id: 'PAP', name: 'Papum Pare', state: 'Arunachal Pradesh', accessibilityScore: 76, population: 176000, essentialSupplyRisk: 40 },
]
const cargoTypes = ['Emergency Medicine', 'Medical Supplies', 'Disaster Relief', 'Food', 'Essential Commodities', 'Government Supplies', 'General Cargo']
export const missions: Mission[] = Array.from({ length: 42 }, (_, index) => { const corridor = corridors[index % corridors.length]; const priority = [10, 9, 8, 6, 5, 4, 7][index % 7]; return { missionId: `NE-${priority >= 8 ? 'MED' : 'LOG'}-${1042 + index}`, origin: corridor.startLocation, destination: corridor.endLocation, cargoType: cargoTypes[index % cargoTypes.length], priority, vehicleId: `TRK-${String((index % 15) + 1).padStart(3, '0')}`, route: [corridor.id, corridors[(index + 3) % corridors.length].id], estimatedTime: corridor.travelTime, risk: corridor.riskScore, status: index % 5 === 0 ? 'Staged' : 'In Transit', district: corridor.districts[1] } })
export const vehicles: Vehicle[] = Array.from({ length: 15 }, (_, index) => { const mission = missions[index]; return { vehicleId: `TRK-${String(index + 1).padStart(3, '0')}`, missionId: mission.missionId, currentLocation: mission.origin, destination: mission.destination, status: index % 5 === 0 ? 'Staged' : 'Moving', eta: `${Math.floor(mission.estimatedTime / 60)}h ${mission.estimatedTime % 60}m`, route: mission.route } })
