import { corridors, districts, missions, vehicles } from './data'
import type { InterventionPlan, Scenario, SimulationResult } from './types'
const severityFactor = { Moderate: 0.75, High: 1, Critical: 1.3 }
export function simulateScenario(scenario: Scenario): SimulationResult {
  const corridor = corridors.find((item) => item.id === scenario.corridorId) ?? corridors[0]
  const affectedMissions = missions.filter((mission) => mission.route.includes(corridor.id)).map((mission) => ({ ...mission, risk: Math.min(99, Math.round(mission.risk * severityFactor[scenario.severity] + scenario.duration)) }))
  const affectedVehicles = vehicles.filter((vehicle) => affectedMissions.some((mission) => mission.vehicleId === vehicle.vehicleId)).map((vehicle) => ({ ...vehicle, status: 'Delayed' as const }))
  const affectedDistricts = districts.filter((district) => corridor.districts.includes(district.id) || affectedMissions.some((mission) => mission.district === district.id))
  const criticalMissions = affectedMissions.filter((mission) => mission.priority >= 8)
  const factor = severityFactor[scenario.severity] * (0.7 + scenario.duration / 12)
  const alternateRoutes = corridor.alternateRouteIds.flatMap((routeId, index) => { const alt = corridors.find((item) => item.id === routeId); if (!alt) return []; const risk = Math.min(94, Math.round(alt.riskScore * factor)); const eta = Math.round(alt.travelTime + scenario.duration * (index + 1) * 9); const capacityPenalty = alt.capacity === 'Low' ? 18 : alt.capacity === 'Medium' ? 8 : 0; const score = Math.round(risk * 0.52 + eta / 10 + capacityPenalty); return [{ id: alt.id, name: alt.name, eta, risk, disruptionProbability: Math.min(92, risk - 7 + scenario.duration), capacity: alt.capacity, score, missionId: criticalMissions[0]?.missionId ?? 'NETWORK', recommendation: '' }] }).sort((a, b) => a.score - b.score).map((route, index, routes) => ({ ...route, recommendation: index === 0 ? `Recommended: ${Math.max(1, Math.round((routes[routes.length - 1]?.risk - route.risk) / 2))}% lower disruption risk` : 'Contingency route' }))
  const averageDelay = Math.round((scenario.duration * 18 + corridor.riskScore * 0.35) * severityFactor[scenario.severity])
  const criticalMissionRisk = Math.min(96, Math.round(28 + corridor.riskScore * 0.3 + scenario.duration * 1.6 * severityFactor[scenario.severity]))
  const networkRisk = criticalMissionRisk >= 75 ? 'Critical' : criticalMissionRisk >= 52 ? 'High' : 'Moderate'
  return { scenario, affectedMissions, affectedVehicles, affectedDistricts, alternateRoutes, criticalMissions, supplyChainsAtRisk: Math.max(1, Math.min(5, Math.ceil(criticalMissions.length / 2))), networkRisk, averageDelay, criticalMissionRisk, timeline: [{ time: '10:00', event: `${scenario.disruptionType} detected by field network` }, { time: '10:45', event: `Corridor risk reaches ${networkRisk.toUpperCase()}` }, { time: '11:15', event: `${corridor.name} becomes unavailable` }, { time: '11:20', event: `${affectedMissions.length} missions identified as affected` }, { time: '11:22', event: `${criticalMissions.length} critical missions prioritized` }, { time: '11:25', event: 'Risk-aware alternate routes calculated' }] }
}
export function createInterventionPlan(result: SimulationResult): InterventionPlan { const afterRisk = Math.max(12, Math.round(result.criticalMissionRisk * 0.29)); return { afterRisk, delay: Math.max(35, Math.round(result.averageDelay * 0.33)), protected: result.criticalMissions.length, recommendations: [{ title: `Reroute ${result.criticalMissions[0]?.missionId ?? 'critical cargo'}`, reason: 'Use the lowest risk available corridor for emergency cargo.', priority: 'P0', effect: `Reduces disruption risk from ${result.criticalMissionRisk}% to ${afterRisk}%.` }, { title: 'Reserve alternate corridor capacity', reason: 'Protect remaining capacity for medical and relief missions.', priority: 'P0', effect: 'Preserves priority throughput for critical missions.' }, { title: 'Hold non-critical cargo at depot', reason: 'Prevent congestion while the primary route is unavailable.', priority: 'P1', effect: 'Avoids secondary delay during recovery.' }, { title: 'Activate secondary depot', reason: 'Shorten the last-mile distance to impacted districts.', priority: 'P1', effect: 'Improves access resilience.' }, { title: 'Dispatch field verification team', reason: 'Validate corridor conditions before reopening.', priority: 'P2', effect: 'Improves confidence in the next update.' }] } }
export function formatMinutes(minutes: number) { return `${Math.floor(minutes / 60)}h ${String(minutes % 60).padStart(2, '0')}m` }
